server:
  port: 8100
spring:
  application:
    name: JiuFang
  profiles:
    active: local
logging:
  level:
    com.shitouren.core: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

#imagePath: http://3293ha4257.qicp.vip
